#ifndef TEXTVIEWERMODE_H_INCLUDED
#define TEXTVIEWERMODE_H_INCLUDED

typedef enum{
    TEXT_VIEWER_MODES_WRAP,
    TEXT_VIEWER_MODES_UNWRAP,
}TEXT_VIEWER_MODES;

#endif // TEXTVIEWERMODE_H_INCLUDED
